version: '3'
services:
  postgres:
    container_name: harpia-gateway-psql
    image: postgres:13-alpine
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cdav4